apiVersion: apps/v1
kind: Deployment
metadata:
  name:  {{ include "currencyservice.name" . }}
spec:
  selector:
    matchLabels:
      app:  {{ include "currencyservice.name" . }}
  template:
    metadata:
      labels:
        app:  {{ include "currencyservice.name" . }}
    spec:
      terminationGracePeriodSeconds: 5
      containers:
        - name: {{ include "currencyservice.name" . }}
          image: "{{ .Values.DockerRepo }}:{{ .Values.DockerTag }}"
          imagePullPolicy: Always 
          ports:
            - name: grpc
              containerPort: 7000
          env:
          - name: PORT
            value: "7000"
          readinessProbe:
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:7000"]
          livenessProbe:
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:7000"]
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi