apiVersion: v1
kind: Service
metadata:
  name: {{ include "currencyservice.name" . }}
spec:
  type: ClusterIP
  selector:
    app: {{ include "currencyservice.name" . }}
  ports:
  - name: grpc
    port: 7000
    targetPort: 7000